#!/usr/bin/env python3
import flask
import json
import sys
from gnomehat import server
from gnomehat import server_config


if __name__ == '__main__':
    experiments_dir = sys.argv[1]
    config = server_config.get_config(experiments_dir)
    server.run(config)
