#!/usr/bin/env python3
import flask
import json
import sys
from gnomehat import server
from gnomehat import hostinfo


if __name__ == '__main__':
    experiments_dir = sys.argv[1]
    config = hostinfo.get_hostinfo(experiments_dir)
    server.run(config)
