#!/usr/bin/env python
# Creates a snapshot copy of this repository in target_dir
# The copy should include any uncommitted or unstaged changes
# (This makes experiments reproducible, even if they're not checked in)
import os
import stat
import sys
import uuid
import os
import subprocess
import shutil
import requests
import argparse
import json

from gnomehat.console import run

USAGE = '''
gnomehat_run: Run a shell command as a Gnomehat experiment

Usage:
    gnomehat_run [-m "message"] [-n namespace] <command ...>

Examples:
    gnomehat python main.py
    gnomehat python my_experiment_with_args.py --arg1 foo --arg2 bar
    gnomehat -m "Add frob layers" python main.py --frob=True
'''


if __name__ == '__main__':
    # Parse args, print usage and quit on error
    try:
        options = run.parse_args(sys.argv)
    except ValueError:
        print(USAGE)
        exit(1)

    run.gnomehat_run(options)
