#!/usr/bin/env python3
import json
import os
import sys
import subprocess
import socket
import time
from gnomehat import sysinfo
from gnomehat import hostinfo
from gnomehat.file_input import read_directory_name, read_option

# The system consists of one server process (the GUI) and many workers
# One worker should be alive per GPU of any connected machine
def gnomehat_start(experiments_dir):
    # Check the server, restart it if needed
    if hostinfo.server_ok(experiments_dir):
        print('Host: Nothing to do, server is already running')
    else:
        run_server(experiments_dir)

    # HACK: kill and restart all the workers
    # TODO: proper daemonization, maybe supervisord, maybe upstart?
    print('Killing all workers...')
    os.system('pkill -f gnomehat_worker')
    print('All workers killed, ready to relaunch.')

    # For each GPU, generate a worker with CUDA_VISIBLE_DEVICES set
    gpus = sysinfo.get_gpu_info()
    for gpu_idx, gpu in enumerate(gpus):
        print('Starting worker for GPU {} ({})...'.format(gpu_idx, gpu['name']))
        run_worker(experiments_dir, gpu_idx)
        print('Started worker for GPU {}'.format(gpu_idx))
    print('All workers started')
    self_check(experiments_dir)


def self_check(experiments_dir):
    print('GnomeHat running self-check...')
    time.sleep(2)
    info = hostinfo.get_hostinfo(experiments_dir)
    print('GnomeHat UI is now running at:')
    print('\t{}'.format(info['gui_url']))


def run_worker(experiments_dir, gpu_idx):
    # HACK: nohup with output redirected instead of a proper daemon
    # Redirect stdout and stderr to a worker log file
    os.environ['CUDA_VISIBLE_DEVICES'] = str(gpu_idx)
    log_filename = '{}/worker_{}_{}.txt'.format(experiments_dir, socket.gethostname(), gpu_idx)
    cmd = 'nohup gnomehat_worker {} >> {} 2>&1 &'.format(experiments_dir, log_filename)
    os.system(cmd)


def run_server(experiments_dir):
    print('Starting server at {}...'.format(experiments_dir))
    cmd = 'nohup gnomehat_server {0} > {0}/server.txt 2>&1 &'.format(experiments_dir)
    os.system(cmd)
    print('Server started at {}'.format(experiments_dir))


def gnomehat_stop():
    # TODO: Send a special signal maybe?
    os.system('pkill -f gnomehat_server')
    os.system('pkill -f gnomehat_worker')
    # TODO: Mark jobs as cancelled so they don't stay eternally 'still running'


def check_gpus():
    gpus = sysinfo.get_gpu_info()
    print('GnomeHat initializing...')
    print('Found {} GPUs:'.format(len(gpus)))
    for gpu in gpus:
        print('\t{}'.format(gpu['name']))


def gnomehat_restart_server(experiments_dir):
    os.system('pkill -f gnomehat_server')
    run_server(experiments_dir)


def load_config_file():
    config_path = os.path.expanduser('~/.gnomehat')
    try:
        cfg = json.loads(open(config_path).read())
        if 'experiments_dir' not in cfg:
            return False
    except:
        return False
    return cfg


def save_config_file(config):
    config_path = os.path.expanduser('~/.gnomehat')
    print('Saving JSON config {} to file {}'.format(config, config_path))
    with open(config_path, 'w') as fp:
        fp.write(json.dumps(config, indent=2))


def get_experiments_dir():
    if len(sys.argv) == 3:
        experiments_dir = sys.argv[2]
    elif os.environ.get('GNOMEHAT_DIR'):
        experiments_dir = os.environ['GNOMEHAT_DIR']
    elif load_config_file():
        experiments_dir = load_config_file()['experiments_dir']
    else:
        experiments_dir = prompt_create_experiments_dir()
    print('Using experiments_dir: {}'.format(experiments_dir))
    os.makedirs(experiments_dir, exist_ok=True)
    return experiments_dir

def prompt_create_experiments_dir():
    print('\n')
    print('Hello!')
    print('It looks like this is your first time running gnomehat')
    print('(The GNOMEHAT_DIR variable has not been set.)')
    print('\n')
    print('Please choose a directory where your experiments should be stored.')
    print('Enter a directory name (eg. /home/username/experiments)')
    experiments_dir = read_directory_name()
    print('\n')

    print('Now using {} as the GNOMEHAT_DIR'.format(experiments_dir))
    save_config_file({'experiments_dir': experiments_dir})
    print("")

    print("")
    print('Which way would you like Gnomehat to run Python?')
    print("    (If you're not sure, select option #1)")
    print("")
    selection = read_option({
        'miniconda': 'Run Gnomehat with Python 3.7 at {}/env'.format(experiments_dir),
        'nothing': 'Use your current Python at: {}'.format(which_python()),
    })
    if selection == 'nothing':
        print('Gnomehat will use the current Python: {}'.format(which_python()))
    else:
        print('Installing Gnomehat-only Python to {}/env'.format(experiments_dir))
        install_miniconda_python(experiments_dir)
        print('Gnomehat will use Miniconda Python at {}'.format(experiments_dir))
    print("")

    return experiments_dir


def install_miniconda_python(experiments_dir):
    cmd = ['gnomehat_install_standalone_python', os.path.join(experiments_dir, 'env')]
    subprocess.run(cmd)


def which_python():
    return str(subprocess.check_output(['which', 'python']), 'utf').strip()


def gnomehat_demo(experiments_dir, demo_name):
    TMP_DIR = '/tmp'
    os.chdir(TMP_DIR)

    # TODO: Set up dedicated org for demo zoo
    DEMOS_GIT_URL = 'https://github.com/lwneal/'
    clone_cmd = ['git', 'clone', '{}/{}'.format(DEMOS_GIT_URL, demo_name)]
    subprocess.run(clone_cmd)
    os.chdir(demo_name)

    run_cmd = ['gnomehat', 'python', 'main.py']
    subprocess.run(run_cmd)


def gnomehat_logs(experiments_dir):
    # todo: security lol
    os.system('tail -f {}/*.txt'.format(experiments_dir))


if __name__ == '__main__':
    if len(sys.argv) < 2 or '--help' in sys.argv:
        print('Command-line interface for Gnomehat, the simple experiment tracker')
        print('Usage:')
        print('\tgnomehat start [experiments_dir]')
        print('\tgnomehat restart')
        print('\tgnomehat stop')
        print('\tgnomehat status')
        print('\tgnomehat logs')
        print('\tgnomehat run [-n namespace] [-m message] <command...>')
        print('Note: "gnomehat" is an alias to "gnomehat run"')
        exit(1)
    command = sys.argv[1]
    if command == 'start':
        check_gpus()
        experiments_dir = get_experiments_dir()
        gnomehat_start(experiments_dir)
    elif command == 'stop':
        print('Terminating all gnomehat processes...')
        gnomehat_stop()
    elif command == 'restart':
        print('Restarting...')
        experiments_dir = get_experiments_dir()
        gnomehat_stop()
        gnomehat_start(experiments_dir)
    elif command == 'status':
        print('The following gnomehat processes are running:')
        os.system('pgrep -a gnomehat')
    elif command == 'restart-server':
        experiments_dir = get_experiments_dir()
        gnomehat_restart_server(experiments_dir)
    elif command == 'demo':
        experiments_dir = get_experiments_dir()
        demo_name = sys.argv[2]
        gnomehat_demo(experiments_dir, demo_name)
    elif command == 'logs':
        experiments_dir = get_experiments_dir()
        gnomehat_logs(experiments_dir)
    else:
        # The command 'gnomehat python train.py' is an alias for gnomehat_run
        subprocess.run(['gnomehat_run'] + sys.argv[1:])
